import { DifficultyLevel, Meal, MealType } from '@/utils/types/meals';

export const mealsData: Meal[] = [
  {
    title: 'Juicy Cheese Burger',
    slug: 'juicy-cheese-burger',
    image: '/placeholder.png',
    description:
      'A mouth-watering burger with a juicy beef patty and melted cheese, served in a soft bun.',
    ingredients: [
      { text: 'Ground beef', amount: '200g' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
      { text: 'Burger bun', amount: '1' },
      { text: 'Lettuce', amount: '1 leaf' },
      { text: 'Tomato', amount: '2 slices' },
      { text: 'Cheese slice', amount: '1' },
      { text: 'Oil', amount: '1 tbsp' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Easy,
    tags: [
      'crowd_pleaser',
      'kid_friendly',
      'lazy_night',
      'budget',
      'weeknight',
      'comfort_food',
      'party',
    ],
    instructions: [
      {
        image: '/placeholder.png',
        text: 'Prepare the patty: Mix 200g of ground beef with salt and pepper. Form into a patty.',
      },
      {
        image: '/placeholder.png',
        text: 'Cook the patty: Heat a pan with a bit of oil. Cook the patty for 2-3 minutes each side, until browned.',
      },
      {
        image: '/placeholder.png',
        text: 'Assemble the burger: Toast the bun. Add lettuce, tomato, patty, cheese.',
      },
      { image: '/placeholder.png', text: 'Serve: Add top bun and serve hot.' },
    ],
    cookTime: 25,
    nutritionInfo: {
      calories: 650,
      protein: 32,
      carbs: 45,
      fat: 32,
    },
  },
  {
    title: 'Spicy Curry',
    slug: 'spicy-curry',
    image: '/placeholder.png',
    description: 'A rich and spicy curry, infused with exotic spices and creamy coconut milk.',
    ingredients: [
      { text: 'Mixed vegetables', amount: '400g' },
      { text: 'Curry paste', amount: '2 tbsp' },
      { text: 'Coconut milk', amount: '500ml' },
      { text: 'Oil', amount: '2 tbsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Medium,
    tags: [
      'one_pot',
      'minimal_cleanup',
      'meal_prep',
      'freezer_friendly',
      'spicy',
      'budget',
      'weeknight',
      'comfort_food',
      'party',
      'high_fiber',
      'iron_rich',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Chop vegetables.' },
      { image: '/placeholder.png', text: 'Sauté vegetables in oil.' },
      { image: '/placeholder.png', text: 'Add curry paste and cook 1 min.' },
      { image: '/placeholder.png', text: 'Simmer with coconut milk ~15 min.' },
      { image: '/placeholder.png', text: 'Serve with rice.' },
    ],
    cookTime: 35,
    nutritionInfo: {
      calories: 550,
      protein: 18,
      carbs: 50,
      fat: 28,
    },
  },
  {
    title: 'Homemade Dumplings',
    slug: 'homemade-dumplings',
    image: '/placeholder.png',
    description: 'Tender dumplings with savory filling, steamed to perfection.',
    ingredients: [
      { text: 'Minced meat', amount: '200g' },
      { text: 'Shredded vegetables', amount: '100g' },
      { text: 'Spices', amount: '1 tsp' },
      { text: 'Dumpling wrappers', amount: '12' },
    ],
    mealType: [MealType.Snacks],
    difficulty: DifficultyLevel.Medium,
    tags: ['crowd_pleaser', 'freezer_friendly', 'budget', 'party', 'weeknight', 'comfort_food'],
    instructions: [
      { image: '/placeholder.png', text: 'Mix filling.' },
      { image: '/placeholder.png', text: 'Fill and seal wrappers.' },
      { image: '/placeholder.png', text: 'Steam ~10 min.' },
      { image: '/placeholder.png', text: 'Serve hot.' },
    ],
    cookTime: 32,
    nutritionInfo: {
      calories: 480,
      protein: 20,
      carbs: 50,
      fat: 15,
    },
  },
  {
    title: 'Classic Mac n Cheese',
    slug: 'classic-mac-n-cheese',
    image: '/placeholder.png',
    description: 'Creamy cheesy macaroni comfort dish.',
    ingredients: [
      { text: 'Macaroni', amount: '250g' },
      { text: 'Butter', amount: '2 tbsp' },
      { text: 'Flour', amount: '2 tbsp' },
      { text: 'Milk', amount: '400ml' },
      { text: 'Grated cheese', amount: '150g' },
      { text: 'Breadcrumbs', amount: '30g' },
      { text: 'Parsley', amount: '1 tbsp (optional)' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Easy,
    tags: ['one_pot', 'crowd_pleaser', 'kid_friendly', 'lazy_night', 'comfort_food', 'weeknight'],
    instructions: [
      { image: '/placeholder.png', text: 'Cook pasta.' },
      { image: '/placeholder.png', text: 'Make roux with butter+flour, add milk.' },
      { image: '/placeholder.png', text: 'Melt in cheese, combine pasta.' },
      { image: '/placeholder.png', text: 'Top with breadcrumbs, bake briefly.' },
    ],
    cookTime: 30,
    nutritionInfo: {
      calories: 700,
      protein: 25,
      carbs: 65,
      fat: 32,
    },
  },
  {
    title: 'Authentic Pizza',
    slug: 'authentic-pizza',
    image: '/placeholder.png',
    description: 'Hand-tossed pizza with fresh toppings.',
    ingredients: [
      { text: 'Pizza dough', amount: '1 ball' },
      { text: 'Tomato sauce', amount: '100g' },
      { text: 'Cheese', amount: '100g' },
      { text: 'Favorite toppings', amount: 'as desired' },
      { text: 'Basil leaves', amount: 'a few' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Medium,
    tags: [
      'crowd_pleaser',
      'kid_friendly',
      'party',
      'lazy_night',
      'budget',
      'party',
      'weeknight',
      'comfort_food',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Stretch dough.' },
      { image: '/placeholder.png', text: 'Add sauce and toppings.' },
      { image: '/placeholder.png', text: 'Bake at high heat.' },
      { image: '/placeholder.png', text: 'Garnish with basil.' },
    ],
    cookTime: 40,
    nutritionInfo: {
      calories: 720,
      protein: 28,
      carbs: 70,
      fat: 30,
    },
  },
  {
    title: 'Wiener Schnitzel',
    slug: 'wiener-schnitzel',
    image: '/placeholder.png',
    description: 'Crispy breaded veal cutlet.',
    ingredients: [
      { text: 'Veal cutlets', amount: '2' },
      { text: 'Flour', amount: '50g' },
      { text: 'Eggs', amount: '2' },
      { text: 'Breadcrumbs', amount: '100g' },
      { text: 'Oil', amount: 'for frying' },
      { text: 'Lemon', amount: '1 slice' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Medium,
    tags: ['crowd_pleaser', 'comfort_food', 'weeknight', 'date_night', 'iron_rich'],
    instructions: [
      { image: '/placeholder.png', text: 'Prepare breading stations.' },
      { image: '/placeholder.png', text: 'Coat cutlets flour, egg, crumbs.' },
      { image: '/placeholder.png', text: 'Fry until golden.' },
      { image: '/placeholder.png', text: 'Serve with lemon.' },
    ],
    cookTime: 25,
    nutritionInfo: {
      calories: 680,
      protein: 34,
      carbs: 40,
      fat: 35,
    },
  },
  {
    title: 'Fresh Tomato Salad',
    slug: 'fresh-tomato-salad',
    image: '/placeholder.png',
    description: 'Refreshing tomato basil salad.',
    ingredients: [
      { text: 'Fresh tomatoes', amount: '2' },
      { text: 'Basil', amount: 'a handful' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
      { text: 'Olive oil', amount: '2 tbsp' },
      { text: 'Balsamic vinegar', amount: '1 tbsp' },
    ],
    mealType: [MealType.Lunch],
    difficulty: DifficultyLevel.Easy,
    tags: [
      'simple_5_ingredients',
      'minimal_cleanup',
      'budget',
      'light_meal',
      'lunchbox',
      'low_sodium',
      'high_fiber',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Slice tomatoes.' },
      { image: '/placeholder.png', text: 'Add basil and season.' },
      { image: '/placeholder.png', text: 'Dress with oil & vinegar.' },
      { image: '/placeholder.png', text: 'Toss and serve.' },
    ],
    cookTime: 10,
    nutritionInfo: {
      calories: 180,
      protein: 4,
      carbs: 12,
      fat: 12,
    },
  },
  {
    title: 'Creamy Mushroom Risotto',
    slug: 'creamy-mushroom-risotto',
    image: '/placeholder.png',
    description: 'Silky Arborio rice cooked slowly with sautéed mushrooms and parmesan.',
    ingredients: [
      { text: 'Arborio rice', amount: '200g' },
      { text: 'Mushrooms', amount: '150g' },
      { text: 'Onion', amount: '1 small' },
      { text: 'Garlic', amount: '2 cloves' },
      { text: 'Vegetable broth', amount: '700ml' },
      { text: 'Parmesan', amount: '40g' },
      { text: 'Butter', amount: '1 tbsp' },
      { text: 'Olive oil', amount: '1 tbsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Hard,
    tags: [
      'one_pot',
      'minimal_cleanup',
      'crowd_pleaser',
      'comfort_food',
      'weeknight',
      'date_night',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Sauté chopped onion & garlic in oil.' },
      { image: '/placeholder.png', text: 'Add sliced mushrooms; cook until soft.' },
      { image: '/placeholder.png', text: 'Stir in rice; toast 1–2 min.' },
      { image: '/placeholder.png', text: 'Add broth gradually, stirring until absorbed.' },
      { image: '/placeholder.png', text: 'Finish with butter & parmesan; season.' },
    ],
    cookTime: 35,
    nutritionInfo: {
      calories: 600,
      protein: 16,
      carbs: 70,
      fat: 24,
    },
  },
  {
    title: 'Lemon Herb Grilled Chicken',
    slug: 'lemon-herb-grilled-chicken',
    image: '/placeholder.png',
    description: 'Juicy chicken breasts marinated in lemon, garlic, and fresh herbs.',
    ingredients: [
      { text: 'Chicken breasts', amount: '2' },
      { text: 'Lemon juice', amount: '2 tbsp' },
      { text: 'Olive oil', amount: '1 tbsp' },
      { text: 'Garlic', amount: '2 cloves' },
      { text: 'Fresh thyme', amount: '1 tsp' },
      { text: 'Fresh rosemary', amount: '1 tsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Easy,
    tags: ['meal_prep', 'lunch_friendly', 'weeknight', 'light_meal', 'post_workout'],
    instructions: [
      { image: '/placeholder.png', text: 'Mix marinade ingredients.' },
      { image: '/placeholder.png', text: 'Coat chicken; rest 20 min.' },
      { image: '/placeholder.png', text: 'Grill each side until cooked.' },
      { image: '/placeholder.png', text: 'Rest briefly; slice & serve.' },
    ],
    cookTime: 30,
    nutritionInfo: {
      calories: 450,
      protein: 38,
      carbs: 8,
      fat: 24,
    },
  },
  {
    title: 'Vegan Quinoa Bowl',
    slug: 'vegan-quinoa-bowl',
    image: '/placeholder.png',
    description: 'Protein-packed quinoa with roasted veggies and tahini drizzle.',
    ingredients: [
      { text: 'Quinoa', amount: '150g' },
      { text: 'Broccoli florets', amount: '100g' },
      { text: 'Sweet potato', amount: '1 small' },
      { text: 'Chickpeas', amount: '100g' },
      { text: 'Olive oil', amount: '2 tbsp' },
      { text: 'Tahini', amount: '1 tbsp' },
      { text: 'Lemon juice', amount: '1 tbsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Lunch],
    difficulty: DifficultyLevel.Medium,
    tags: [
      'meal_prep',
      'lunch_friendly',
      'one_pot',
      'minimal_cleanup',
      'light_meal',
      'lunchbox',
      'weeknight',
      'high_fiber',
      'iron_rich',
      'post_workout',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Roast chopped veggies & chickpeas.' },
      { image: '/placeholder.png', text: 'Cook quinoa until fluffy.' },
      { image: '/placeholder.png', text: 'Whisk tahini, lemon, salt, pepper.' },
      { image: '/placeholder.png', text: 'Assemble bowl; drizzle sauce.' },
    ],
    cookTime: 35,
    nutritionInfo: {
      calories: 520,
      protein: 20,
      carbs: 60,
      fat: 18,
    },
  },
  {
    title: 'Garlic Butter Shrimp Pasta',
    slug: 'garlic-butter-shrimp-pasta',
    image: '/placeholder.png',
    description: 'Tender shrimp tossed with spaghetti in a garlic butter sauce.',
    ingredients: [
      { text: 'Spaghetti', amount: '180g' },
      { text: 'Shrimp (peeled)', amount: '200g' },
      { text: 'Butter', amount: '2 tbsp' },
      { text: 'Garlic', amount: '3 cloves' },
      { text: 'Parsley', amount: '1 tbsp' },
      { text: 'Lemon zest', amount: '1 tsp' },
      { text: 'Olive oil', amount: '1 tsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Medium,
    tags: ['one_pot', 'crowd_pleaser', 'date_night', 'weeknight', 'comfort_food'],
    instructions: [
      { image: '/placeholder.png', text: 'Cook pasta al dente.' },
      { image: '/placeholder.png', text: 'Sauté garlic in butter & oil.' },
      { image: '/placeholder.png', text: 'Add shrimp; cook until pink.' },
      { image: '/placeholder.png', text: 'Toss with pasta, parsley, lemon.' },
    ],
    cookTime: 25,
    nutritionInfo: {
      calories: 560,
      protein: 30,
      carbs: 55,
      fat: 22,
    },
  },
  {
    title: 'Tofu Stir Fry',
    slug: 'tofu-stir-fry',
    image: '/placeholder.png',
    description: 'Quick stir fry with crispy tofu and colorful vegetables.',
    ingredients: [
      { text: 'Firm tofu', amount: '200g' },
      { text: 'Bell pepper', amount: '1' },
      { text: 'Snow peas', amount: '80g' },
      { text: 'Soy sauce', amount: '2 tbsp' },
      { text: 'Sesame oil', amount: '1 tsp' },
      { text: 'Garlic', amount: '2 cloves' },
      { text: 'Ginger', amount: '1 tsp' },
      { text: 'Cornstarch', amount: '1 tsp' },
      { text: 'Oil', amount: '1 tbsp' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Easy,
    tags: [
      'one_pot',
      'minimal_cleanup',
      'meal_prep',
      'lunch_friendly',
      'weeknight',
      'light_meal',
      'high_fiber',
      'post_workout',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Press & cube tofu; toss in cornstarch.' },
      { image: '/placeholder.png', text: 'Pan-fry tofu until golden.' },
      { image: '/placeholder.png', text: 'Stir fry veggies with aromatics.' },
      { image: '/placeholder.png', text: 'Add tofu & sauce; toss to coat.' },
    ],
    cookTime: 20,
    nutritionInfo: {
      calories: 420,
      protein: 22,
      carbs: 30,
      fat: 20,
    },
  },
  {
    title: 'Greek Salad Bowl',
    slug: 'greek-salad-bowl',
    image: '/placeholder.png',
    description: 'Classic Mediterranean salad with feta, olives, and crisp veggies.',
    ingredients: [
      { text: 'Cucumber', amount: '1/2' },
      { text: 'Tomatoes', amount: '2' },
      { text: 'Red onion', amount: '1/4' },
      { text: 'Feta cheese', amount: '60g' },
      { text: 'Olives', amount: '40g' },
      { text: 'Olive oil', amount: '2 tbsp' },
      { text: 'Red wine vinegar', amount: '1 tbsp' },
      { text: 'Oregano', amount: '1/2 tsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Lunch],
    difficulty: DifficultyLevel.Easy,
    tags: [
      'simple_5_ingredients',
      'minimal_cleanup',
      'lunch_friendly',
      'budget',
      'light_meal',
      'lunchbox',
      'weeknight',
      'low_sodium',
      'high_fiber',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Chop vegetables evenly.' },
      { image: '/placeholder.png', text: 'Combine in a large bowl.' },
      { image: '/placeholder.png', text: 'Whisk dressing ingredients.' },
      { image: '/placeholder.png', text: 'Toss salad; top with feta.' },
    ],
    cookTime: 15,
    nutritionInfo: {
      calories: 350,
      protein: 10,
      carbs: 18,
      fat: 26,
    },
  },
  {
    title: 'Beef Chili',
    slug: 'beef-chili',
    image: '/placeholder.png',
    description: 'Hearty chili with beans, spices, and slow-simmered beef.',
    ingredients: [
      { text: 'Ground beef', amount: '300g' },
      { text: 'Kidney beans', amount: '150g' },
      { text: 'Tomato puree', amount: '200g' },
      { text: 'Onion', amount: '1' },
      { text: 'Chili powder', amount: '1 tbsp' },
      { text: 'Cumin', amount: '1 tsp' },
      { text: 'Garlic', amount: '2 cloves' },
      { text: 'Oil', amount: '1 tbsp' },
      { text: 'Salt', amount: 'to taste' },
      { text: 'Pepper', amount: 'to taste' },
    ],
    mealType: [MealType.Dinner],
    difficulty: DifficultyLevel.Medium,
    tags: [
      'one_pot',
      'meal_prep',
      'freezer_friendly',
      'crowd_pleaser',
      'budget',
      'weeknight',
      'comfort_food',
      'party',
      'iron_rich',
    ],
    instructions: [
      { image: '/placeholder.png', text: 'Brown beef with onion & garlic.' },
      { image: '/placeholder.png', text: 'Stir in spices; cook briefly.' },
      { image: '/placeholder.png', text: 'Add beans & tomato; simmer.' },
      { image: '/placeholder.png', text: 'Adjust seasoning; serve warm.' },
    ],
    cookTime: 62,
    nutritionInfo: {
      calories: 640,
      protein: 35,
      carbs: 45,
      fat: 30,
    },
  },
  {
    title: 'Overnight Oats',
    slug: 'overnight-oats',
    image: '/placeholder.png',
    description: 'Creamy soaked oats with chia, fruit, and maple sweetness.',
    ingredients: [
      { text: 'Rolled oats', amount: '60g' },
      { text: 'Chia seeds', amount: '1 tbsp' },
      { text: 'Milk (dairy or plant)', amount: '150ml' },
      { text: 'Maple syrup', amount: '1 tsp' },
      { text: 'Blueberries', amount: '40g' },
      { text: 'Vanilla extract', amount: '1/4 tsp' },
      { text: 'Salt', amount: 'pinch' },
    ],
    mealType: [MealType.Breakfast],
    difficulty: DifficultyLevel.Easy,
    tags: ['meal_prep', 'simple_5_ingredients', 'budget', 'light_meal', 'high_fiber'],
    instructions: [
      { image: '/placeholder.png', text: 'Combine oats, chia, milk, sweetener.' },
      { image: '/placeholder.png', text: 'Stir; refrigerate overnight.' },
      { image: '/placeholder.png', text: 'Top with fruit & serve.' },
    ],
    cookTime: 5, // active time; overnight is passive
    nutritionInfo: {
      calories: 320,
      protein: 10,
      carbs: 45,
      fat: 9,
    },
  },
];
